### PR TITLE
license: use gpl

### PR DESCRIPTION
**Pull request by Supercip971**

### CODE REVIEW

**Comment by Supercip971** [comment]
better, rms approved, and stronger

**Comment by d0p1s4m4** [comment]
+1

**Comment by keyboard-slayer** [comment]
based

**Comment by leapofazzam123** [comment]
based

**Comment by sleepy-monax** [comment]
https://commons.wikimedia.org/wiki/File:GPLv3_Logo.svg

**Comment by robot-stallman** [comment]
I'm approving this

**Review by robot-stallman — APPROVED** [review]
this is pog

**Review by Rheydskey — APPROVED** [review]

**Review by keyboard-slayer — APPROVED** [review]
Stallman would be proud of you 😍

**Comment by robot-stallman** [comment]
> Stallman would be proud of you heart_eyes

I am

**Review by Woomymy — APPROVED** [review]
Join us now and share the software :notes:, You'll be free, hackers, you'll be free

**Review by d0p1s4m4 — APPROVED** [review]

**Comment by d0p1s4m4** [comment]
> Why GPL if I may ask?
> 
> For practical (incl. industry) use in the wild would MIT be undoubtedly much better.

The GPL guarantees respect for the 4 freedoms which the MIT does not guarantee. Code licensed under the MIT license can therefore be enclosed in proprietary software.

I don't see how the GPL would be less practical for the industry? On the contrary, for an open-source project, the GPL is the most suitable license: it forces companies to give back to the community. (you must share the modified source code under the same license, you must publish the source code etc)

**Review by leapofazzam123 — APPROVED** [review]

**Comment by keyboard-slayer** [comment]
index

**Comment by leapofazzam123** [comment]
petition to cancel @sleepy-monax on twitter

**Comment by keyboard-slayer** [comment]
Oh no

**Pull request closed without merging**
