### PR TITLE
make the kernel great again (not a c++ rewrite)

### PR DESCRIPTION
**Pull request by Supercip971**
now we can say that brutal is perfection ! (uwu)

### CODE REVIEW

**Comment by Supercip971** [comment]
+ if the CI fail, it means it's bloated

**Comment by sleepy-monax** [comment]
make brutal **cute** again

**Comment by keyboard-slayer** [comment]
Looks legit good to me :heart_eyes:

**Review by keyboard-slayer — APPROVED** [review]

**Comment by sleepy-monax** [comment]
Loader should be renamed lowoder

**Comment by sleepy-monax** [comment]
Also rewrite in rust

**Comment by keyboard-slayer** [comment]
> Also rewrite in rust

No, rewrite it in solidity and make the FS blockchain based

**Pull request closed without merging**
