### PR TITLE
readme: more professional styling on the roadmap section

### PR DESCRIPTION
**Pull request by leapofazzam123**
"Right now the main goal of brutal is to run doom." sounds like a child wrote it

### CODE REVIEW

**Comment by sleepy-monax** [comment]
> sounds like a child wrote it

What do you mean by that ?

**Comment by leapofazzam123** [comment]
- Its all lowercase
- > the main goal of brutal is to run doom.

  no we're not porting doom right now, its not milestone 6

**Comment by keyboard-slayer** [comment]
What if we want to re-find our inner child ? 

Brutal doesn't want to be professional so who cares really ?

Imagine making an os to look like an adult big meme :^)

**Comment by leapofazzam123** [comment]
💀

**Pull request closed without merging**
